notifications:
  slack: twhelp:MLxYcBP5Nd7mx9wqLhLeXBCK

language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2

services: 
    - docker
    
script:
    - dotnet restore TWHelp/TWHelp.csproj
    - dotnet build TWHelp/TWHelp.csproj
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1